//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopoHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1E-06")]
        public double APP_EPSILON {
            get {
                return ((double)(this["APP_EPSILON"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double DV_LRTRR_TOLERANCE {
            get {
                return ((double)(this["DV_LRTRR_TOLERANCE"]));
            }
            set {
                this["DV_LRTRR_TOLERANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2D-")]
        public string LAY_NAME_PREFIX_2D {
            get {
                return ((string)(this["LAY_NAME_PREFIX_2D"]));
            }
            set {
                this["LAY_NAME_PREFIX_2D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3D-")]
        public string LAY_NAME_PREFIX_3D {
            get {
                return ((string)(this["LAY_NAME_PREFIX_3D"]));
            }
            set {
                this["LAY_NAME_PREFIX_3D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("811")]
        public string LAY_NAME_R2R_CL {
            get {
                return ((string)(this["LAY_NAME_R2R_CL"]));
            }
            set {
                this["LAY_NAME_R2R_CL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("253")]
        public short LAY_COL_R2R_CL_PL {
            get {
                return ((short)(this["LAY_COL_R2R_CL_PL"]));
            }
            set {
                this["LAY_COL_R2R_CL_PL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DRAW_3D_R2R_CL_PNTS {
            get {
                return ((bool)(this["DRAW_3D_R2R_CL_PNTS"]));
            }
            set {
                this["DRAW_3D_R2R_CL_PNTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("811-Points")]
        public string LAY_NAME_R2R_CL_PNTS {
            get {
                return ((string)(this["LAY_NAME_R2R_CL_PNTS"]));
            }
            set {
                this["LAY_NAME_R2R_CL_PNTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("251")]
        public short LAY_COL_R2D_CL_PNTS {
            get {
                return ((short)(this["LAY_COL_R2D_CL_PNTS"]));
            }
            set {
                this["LAY_COL_R2D_CL_PNTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.6")]
        public double DV_LRTRR_MAX_VALUE {
            get {
                return ((double)(this["DV_LRTRR_MAX_VALUE"]));
            }
            set {
                this["DV_LRTRR_MAX_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DRAW_2D_R2R_CL_PL {
            get {
                return ((bool)(this["DRAW_2D_R2R_CL_PL"]));
            }
            set {
                this["DRAW_2D_R2R_CL_PL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DRAW_3D_R2R_CL_PL {
            get {
                return ((bool)(this["DRAW_3D_R2R_CL_PL"]));
            }
            set {
                this["DRAW_3D_R2R_CL_PL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Data\\track.R2R.csv")]
        public string IO_FILE_R2R_CSV {
            get {
                return ((string)(this["IO_FILE_R2R_CSV"]));
            }
            set {
                this["IO_FILE_R2R_CSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CALCULATE_CSD {
            get {
                return ((bool)(this["CALCULATE_CSD"]));
            }
            set {
                this["CALCULATE_CSD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DRAW_3D_CSD_RAILS_PL {
            get {
                return ((bool)(this["DRAW_3D_CSD_RAILS_PL"]));
            }
            set {
                this["DRAW_3D_CSD_RAILS_PL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IAMTopo_CorrectSurveyDisplacementRail")]
        public string LAY_NAME_CSD_RAILS_PL {
            get {
                return ((string)(this["LAY_NAME_CSD_RAILS_PL"]));
            }
            set {
                this["LAY_NAME_CSD_RAILS_PL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DRAW_2D_R2R_CL_PNTS {
            get {
                return ((bool)(this["DRAW_2D_R2R_CL_PNTS"]));
            }
            set {
                this["DRAW_2D_R2R_CL_PNTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LOG_R2R_CSV {
            get {
                return ((bool)(this["LOG_R2R_CSV"]));
            }
            set {
                this["LOG_R2R_CSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string IO_FILE_R2R_CSV_DELIMITER {
            get {
                return ((string)(this["IO_FILE_R2R_CSV_DELIMITER"]));
            }
            set {
                this["IO_FILE_R2R_CSV_DELIMITER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110")]
        public short LAY_COL_CSD_RAILS_PL {
            get {
                return ((short)(this["LAY_COL_CSD_RAILS_PL"]));
            }
            set {
                this["LAY_COL_CSD_RAILS_PL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DRAW_3D_CSD_RAILS_PNTS {
            get {
                return ((bool)(this["DRAW_3D_CSD_RAILS_PNTS"]));
            }
            set {
                this["DRAW_3D_CSD_RAILS_PNTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IAMTopo_CorrectSurveyDisplacementRailPoints")]
        public string LAY_NAME_CSD_RAILS_PNTS {
            get {
                return ((string)(this["LAY_NAME_CSD_RAILS_PNTS"]));
            }
            set {
                this["LAY_NAME_CSD_RAILS_PNTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115")]
        public short LAY_COL_CSD_RAILS_PNTS {
            get {
                return ((short)(this["LAY_COL_CSD_RAILS_PNTS"]));
            }
            set {
                this["LAY_COL_CSD_RAILS_PNTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DELETE_JPL_ENTITIES {
            get {
                return ((bool)(this["DELETE_JPL_ENTITIES"]));
            }
            set {
                this["DELETE_JPL_ENTITIES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.005")]
        public double DIST_MIN_PTP {
            get {
                return ((double)(this["DIST_MIN_PTP"]));
            }
            set {
                this["DIST_MIN_PTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double DIST_MAX_PTP {
            get {
                return ((double)(this["DIST_MAX_PTP"]));
            }
            set {
                this["DIST_MAX_PTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Data\\track.CSD.csv")]
        public string IO_FILE_CSD_CSV {
            get {
                return ((string)(this["IO_FILE_CSD_CSV"]));
            }
            set {
                this["IO_FILE_CSD_CSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string IO_FILE_CSD_CSV_DELIMITER {
            get {
                return ((string)(this["IO_FILE_CSD_CSV_DELIMITER"]));
            }
            set {
                this["IO_FILE_CSD_CSV_DELIMITER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Data\\track.DBPL.csv")]
        public string IO_FILE_DBPL_CSV {
            get {
                return ((string)(this["IO_FILE_DBPL_CSV"]));
            }
            set {
                this["IO_FILE_DBPL_CSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string IO_FILE_DBPL_CSV_DELIMITER {
            get {
                return ((string)(this["IO_FILE_DBPL_CSV_DELIMITER"]));
            }
            set {
                this["IO_FILE_DBPL_CSV_DELIMITER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string IO_CSV_NUMBER_DECIMAL_SEPERATOR {
            get {
                return ((string)(this["IO_CSV_NUMBER_DECIMAL_SEPERATOR"]));
            }
            set {
                this["IO_CSV_NUMBER_DECIMAL_SEPERATOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001")]
        public double CSD_MIN_CANT_VAL {
            get {
                return ((double)(this["CSD_MIN_CANT_VAL"]));
            }
            set {
                this["CSD_MIN_CANT_VAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double SYMPPL_TOLERANCE {
            get {
                return ((double)(this["SYMPPL_TOLERANCE"]));
            }
            set {
                this["SYMPPL_TOLERANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SYMPPL_HIGH_PRICISION {
            get {
                return ((bool)(this["SYMPPL_HIGH_PRICISION"]));
            }
            set {
                this["SYMPPL_HIGH_PRICISION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double PLW_WEEDING_DISTANCE {
            get {
                return ((double)(this["PLW_WEEDING_DISTANCE"]));
            }
            set {
                this["PLW_WEEDING_DISTANCE"] = value;
            }
        }
    }
}
