//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace TopoHelper.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1E-06")]
        public double APP_EPSILON {
            get {
                return ((double)(this["APP_EPSILON"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.01")]
        public double DV_LRTRR_TOLERANCE {
            get {
                return ((double)(this["DV_LRTRR_TOLERANCE"]));
            }
            set {
                this["DV_LRTRR_TOLERANCE"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2D-")]
        public string LAY_NAME_PREFIX_2D {
            get {
                return ((string)(this["LAY_NAME_PREFIX_2D"]));
            }
            set {
                this["LAY_NAME_PREFIX_2D"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("3D-")]
        public string LAY_NAME_PREFIX_3D {
            get {
                return ((string)(this["LAY_NAME_PREFIX_3D"]));
            }
            set {
                this["LAY_NAME_PREFIX_3D"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("811")]
        public string LAY_NAME_R2R_CL {
            get {
                return ((string)(this["LAY_NAME_R2R_CL"]));
            }
            set {
                this["LAY_NAME_R2R_CL"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("253")]
        public short LAY_COL_R2R_CL_PL {
            get {
                return ((short)(this["LAY_COL_R2R_CL_PL"]));
            }
            set {
                this["LAY_COL_R2R_CL_PL"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool DRAW_3D_R2R_CL_PNTS {
            get {
                return ((bool)(this["DRAW_3D_R2R_CL_PNTS"]));
            }
            set {
                this["DRAW_3D_R2R_CL_PNTS"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("811-Points")]
        public string LAY_NAME_R2R_CL_PNTS {
            get {
                return ((string)(this["LAY_NAME_R2R_CL_PNTS"]));
            }
            set {
                this["LAY_NAME_R2R_CL_PNTS"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("251")]
        public short LAY_COL_R2D_CL_PNTS {
            get {
                return ((short)(this["LAY_COL_R2D_CL_PNTS"]));
            }
            set {
                this["LAY_COL_R2D_CL_PNTS"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1.6")]
        public double DV_LRTRR_MAX_VALUE {
            get {
                return ((double)(this["DV_LRTRR_MAX_VALUE"]));
            }
            set {
                this["DV_LRTRR_MAX_VALUE"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool DRAW_2D_R2R_CL_PL {
            get {
                return ((bool)(this["DRAW_2D_R2R_CL_PL"]));
            }
            set {
                this["DRAW_2D_R2R_CL_PL"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool DRAW_3D_R2R_CL_PL {
            get {
                return ((bool)(this["DRAW_3D_R2R_CL_PL"]));
            }
            set {
                this["DRAW_3D_R2R_CL_PL"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("c:\\Data\\track.R2R.csv")]
        public string IO_FILE_R2R_CSV {
            get {
                return ((string)(this["IO_FILE_R2R_CSV"]));
            }
            set {
                this["IO_FILE_R2R_CSV"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool CALCULATE_CSD {
            get {
                return ((bool)(this["CALCULATE_CSD"]));
            }
            set {
                this["CALCULATE_CSD"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool DRAW_3D_CSD_RAILS_PL {
            get {
                return ((bool)(this["DRAW_3D_CSD_RAILS_PL"]));
            }
            set {
                this["DRAW_3D_CSD_RAILS_PL"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("IAMTopo_CorrectSurveyDisplacementRail")]
        public string LAY_NAME_CSD_RAILS_PL {
            get {
                return ((string)(this["LAY_NAME_CSD_RAILS_PL"]));
            }
            set {
                this["LAY_NAME_CSD_RAILS_PL"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool DRAW_2D_R2R_CL_PNTS {
            get {
                return ((bool)(this["DRAW_2D_R2R_CL_PNTS"]));
            }
            set {
                this["DRAW_2D_R2R_CL_PNTS"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool LOG_R2R_CSV {
            get {
                return ((bool)(this["LOG_R2R_CSV"]));
            }
            set {
                this["LOG_R2R_CSV"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue(";")]
        public string IO_FILE_R2R_CSV_DELIMITER {
            get {
                return ((string)(this["IO_FILE_R2R_CSV_DELIMITER"]));
            }
            set {
                this["IO_FILE_R2R_CSV_DELIMITER"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("110")]
        public short LAY_COL_CSD_RAILS_PL {
            get {
                return ((short)(this["LAY_COL_CSD_RAILS_PL"]));
            }
            set {
                this["LAY_COL_CSD_RAILS_PL"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool DRAW_3D_CSD_RAILS_PNTS {
            get {
                return ((bool)(this["DRAW_3D_CSD_RAILS_PNTS"]));
            }
            set {
                this["DRAW_3D_CSD_RAILS_PNTS"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("IAMTopo_CorrectSurveyDisplacementRailPoints")]
        public string LAY_NAME_CSD_RAILS_PNTS {
            get {
                return ((string)(this["LAY_NAME_CSD_RAILS_PNTS"]));
            }
            set {
                this["LAY_NAME_CSD_RAILS_PNTS"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("115")]
        public short LAY_COL_CSD_RAILS_PNTS {
            get {
                return ((short)(this["LAY_COL_CSD_RAILS_PNTS"]));
            }
            set {
                this["LAY_COL_CSD_RAILS_PNTS"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool DELETE_JPL_ENTITIES {
            get {
                return ((bool)(this["DELETE_JPL_ENTITIES"]));
            }
            set {
                this["DELETE_JPL_ENTITIES"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.005")]
        public double DIST_MIN_PTP {
            get {
                return ((double)(this["DIST_MIN_PTP"]));
            }
            set {
                this["DIST_MIN_PTP"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.5")]
        public double DIST_MAX_PTP {
            get {
                return ((double)(this["DIST_MAX_PTP"]));
            }
            set {
                this["DIST_MAX_PTP"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("c:\\Data\\track.CSD.csv")]
        public string IO_FILE_CSD_CSV {
            get {
                return ((string)(this["IO_FILE_CSD_CSV"]));
            }
            set {
                this["IO_FILE_CSD_CSV"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue(";")]
        public string IO_FILE_CSD_CSV_DELIMITER {
            get {
                return ((string)(this["IO_FILE_CSD_CSV_DELIMITER"]));
            }
            set {
                this["IO_FILE_CSD_CSV_DELIMITER"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("c:\\Data\\track.DBPL.csv")]
        public string IO_FILE_DBPL_CSV {
            get {
                return ((string)(this["IO_FILE_DBPL_CSV"]));
            }
            set {
                this["IO_FILE_DBPL_CSV"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue(";")]
        public string IO_FILE_DBPL_CSV_DELIMITER {
            get {
                return ((string)(this["IO_FILE_DBPL_CSV_DELIMITER"]));
            }
            set {
                this["IO_FILE_DBPL_CSV_DELIMITER"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue(",")]
        public string IO_CSV_NUMBER_DECIMAL_SEPERATOR {
            get {
                return ((string)(this["IO_CSV_NUMBER_DECIMAL_SEPERATOR"]));
            }
            set {
                this["IO_CSV_NUMBER_DECIMAL_SEPERATOR"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.001")]
        public double CSD_MIN_CANT_VAL {
            get {
                return ((double)(this["CSD_MIN_CANT_VAL"]));
            }
            set {
                this["CSD_MIN_CANT_VAL"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.01")]
        public double SYMPPL_TOLERANCE {
            get {
                return ((double)(this["SYMPPL_TOLERANCE"]));
            }
            set {
                this["SYMPPL_TOLERANCE"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool SYMPPL_HIGH_PRICISION {
            get {
                return ((bool)(this["SYMPPL_HIGH_PRICISION"]));
            }
            set {
                this["SYMPPL_HIGH_PRICISION"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public double PLW_WEEDING_DISTANCE {
            get {
                return ((double)(this["PLW_WEEDING_DISTANCE"]));
            }
            set {
                this["PLW_WEEDING_DISTANCE"] = value;
            }
        }
    }
}
